version: '3.8'

services:
  # Existing Qdrant service
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_vector_db
    ports:
      - "6333:6333" # gRPC port
      - "6334:6334" # REST API port
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6333
      - QDRANT__SERVICE__HTTP_PORT=6334
    restart: unless-stopped
    networks:
      - vector-search-network

  # Neo4j Database Service
  neo4j:
    image: neo4j:latest
    container_name: neo4j-db
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    environment:
      # Set authentication credentials
      NEO4J_AUTH: neo4j/password
      # Set initial heap size
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2G
      # Set to accept license for Neo4j
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      # Persist Neo4j data
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - vector-search-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

networks:
  vector-search-network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: