version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_vector_db
    ports:
      - "6333:6333"  # gRPC port
      - "6334:6334"  # REST API port
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6333
      - QDRANT__SERVICE__HTTP_PORT=6334
    restart: unless-stopped
    networks:
      - vector-search-network

networks:
  vector-search-network:
    driver: bridge